"""
Service page content for Signia Home Care.
Consumer-friendly copy for each service landing page.
Based on Minnesota MDH Comprehensive Home Care and DHS 245D services.
"""

SERVICE_CONTENT = {
    "advanced-practice-nurse-services": {
        "hero_headline": "Advanced Practice Nurse Services",
        "intro": "Advanced Practice Registered Nurses (APRNs) bring specialized nursing expertise to your home. They can assess, diagnose, and manage health conditions, order tests, and coordinate care with your physician.",
        "includes_list": [
            "Health assessments and diagnosis",
            "Medication management and care coordination",
            "Ordering and interpreting tests",
            "Collaboration with your physician",
            "Personalized care plan development",
        ],
        "who_benefits": "Adults and seniors with complex health needs who benefit from advanced nursing oversight at home.",
        "how_helps": "APRN services support better health outcomes, medication management, and care coordination—all in the comfort of home.",
        "what_to_expect": "Your APRN will work with you and your care team to create a plan that supports your health goals. Visits are scheduled based on your needs.",
        "why_signia": "We connect you with qualified APRNs who bring both clinical skill and a compassionate approach to home care.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "registered-nurse-services": {
        "hero_headline": "Registered Nurse Services",
        "intro": "Registered Nurses (RNs) provide skilled nursing care in your home—delivering the same quality of care you'd receive in a facility, in the comfort and familiarity of your own space.",
        "includes_list": [
            "Wound care and dressing changes",
            "Medication management, injections, and IV therapy",
            "Vital sign monitoring and health assessments",
            "Catheter and ostomy care",
            "Disease management education",
            "Coordination with your physician and care team",
        ],
        "who_benefits": "Skilled nursing at home is appropriate for patients recovering from surgery or hospitalization, those with chronic diseases like diabetes or COPD, and anyone requiring wound care or complex medication management.",
        "who_benefits_list": [
            "Patients transitioning from hospital or rehab",
            "Individuals with chronic conditions (diabetes, heart disease, COPD)",
            "Those requiring wound care or complex medication management",
            "People receiving IV medications or tube feedings",
        ],
        "how_helps": "Home-based skilled nursing supports recovery, prevents complications, and helps you manage your health with confidence—all while staying in your familiar environment.",
        "how_helps_list": [
            "Faster recovery in the comfort of home",
            "Reduced risk of hospital readmission",
            "Individualized care tailored to your needs",
            "Typically more affordable than facility-based care",
        ],
        "what_to_expect": "Your care begins with an initial assessment to evaluate your health status and needs. We develop a personalized care plan with you, your family, and your physician, then provide regular visits with ongoing monitoring and adjustments.",
        "what_to_expect_list": [
            "Initial assessment and care plan development",
            "Regular visits according to your care plan",
            "Ongoing coordination with your physician",
            "Family education and updates on your progress",
        ],
        "why_signia": "Our RNs are experienced, caring professionals who treat each client with dignity and respect. We bring clinical excellence and a compassionate approach to every visit.",
        "why_signia_list": [
            "Licensed, experienced RNs",
            "Person-centered care in your home",
            "Seamless coordination with your care team",
            "Compassionate, respectful approach",
        ],
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "licensed-practical-nurse-services": {
        "hero_headline": "Licensed Practical Nurse Services",
        "intro": "Licensed Practical Nurses (LPNs) provide hands-on nursing care under the direction of an RN or physician. They help with medications, wound care, and daily health needs.",
        "includes_list": [
            "Medication administration and monitoring",
            "Wound care and dressing changes",
            "Vital sign monitoring",
            "Basic nursing procedures",
            "Coordination with RN or physician",
        ],
        "who_benefits": "Individuals who need practical nursing support for daily health tasks and monitoring.",
        "how_helps": "LPN services help you stay on track with medications, wound healing, and routine health care at home.",
        "what_to_expect": "Your LPN will follow your care plan and work closely with your RN or physician to ensure continuity of care.",
        "why_signia": "Our LPNs bring skill and compassion to every visit.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "physical-therapy-services": {
        "hero_headline": "Physical Therapy Services",
        "intro": "Physical therapists help improve mobility, strength, balance, and function. In-home PT eliminates the need to travel—we bring expert care to you in your familiar environment.",
        "includes_list": [
            "Comprehensive assessment of your condition and goals",
            "Customized exercise and activity plans",
            "Therapeutic exercises and manual therapy techniques",
            "Home safety evaluation to reduce fall risk",
            "Patient education for self-management between visits",
            "Coordination with your physician and care team",
        ],
        "who_benefits": "Home health physical therapy is ideal for post-surgical patients, stroke survivors, seniors with limited mobility, and anyone with chronic conditions affecting movement.",
        "who_benefits_list": [
            "Individuals recovering from surgery or injury",
            "Stroke survivors regaining function",
            "Seniors with limited mobility or fall risk",
            "Those with chronic pain or arthritis",
        ],
        "how_helps": "In-home PT increases mobility and strength, reduces pain through movement, improves balance to prevent falls, and helps restore functional independence—all without leaving home.",
        "how_helps_list": [
            "One-on-one attention in your home",
            "Treatment tailored to your daily environment",
            "No travel required—saves time and energy",
            "Faster progress in a comfortable setting",
        ],
        "what_to_expect": "Your therapist will conduct an initial assessment, create a personalized plan, and work with you in your home. You'll receive hands-on therapy, targeted exercises, and education to continue progress between visits.",
        "what_to_expect_list": [
            "Initial assessment of your home and abilities",
            "Personalized treatment plan",
            "Regular in-home sessions",
            "Ongoing progress updates to your physician",
        ],
        "why_signia": "We bring physical therapy to you—no need to travel. Our therapists focus on what matters most: your safety, independence, and quality of life.",
        "why_signia_list": [
            "Care in your familiar home environment",
            "Licensed, experienced physical therapists",
            "Focus on your specific daily challenges",
            "Compassionate, goal-oriented approach",
        ],
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "occupational-therapy-services": {
        "hero_headline": "Occupational Therapy Services",
        "intro": "Occupational therapists help you perform everyday activities—dressing, bathing, cooking, and more. They can recommend equipment, modify your environment, and teach new ways to do tasks.",
        "includes_list": [
            "Assessment of daily living skills",
            "Equipment recommendations and training",
            "Home environment modifications",
            "Activity adaptation strategies",
            "Fine motor and coordination exercises",
        ],
        "who_benefits": "Individuals who want to maintain or regain independence with daily activities at home.",
        "how_helps": "OT supports independence, safety, and confidence in daily life.",
        "what_to_expect": "Your therapist will work with you in your home to identify goals and create a practical plan.",
        "why_signia": "Our OTs understand that small changes can make a big difference in how you live each day.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "speech-language-pathologist-services": {
        "hero_headline": "Speech-Language Pathologist Services",
        "intro": "Speech-language pathologists help with communication, swallowing, and cognitive-communication skills. In-home services can support recovery after stroke, manage swallowing difficulties, and improve communication.",
        "includes_list": [
            "Speech and language assessment",
            "Swallowing evaluation and therapy",
            "Communication strategies and exercises",
            "Cognitive-communication support",
            "Diet and feeding recommendations",
        ],
        "who_benefits": "Individuals with speech, language, or swallowing difficulties who benefit from therapy at home.",
        "how_helps": "SLP services support safer eating, clearer communication, and improved quality of life.",
        "what_to_expect": "Your SLP will assess your needs and work with you in your home to reach your goals.",
        "why_signia": "We bring speech and swallowing therapy to you in a familiar, comfortable setting.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "respiratory-therapy-services": {
        "hero_headline": "Respiratory Therapy Services",
        "intro": "Respiratory therapists help manage breathing and lung-related conditions. They can provide treatments, education, and support for oxygen use and breathing equipment.",
        "includes_list": [
            "Breathing treatments and therapies",
            "Oxygen equipment setup and education",
            "Inhaler and medication training",
            "Lung function monitoring",
            "Emergency response planning",
        ],
        "who_benefits": "Individuals with COPD, asthma, or other respiratory conditions who need support at home.",
        "how_helps": "Respiratory therapy supports better breathing, comfort, and independence.",
        "what_to_expect": "Your therapist will work with you and your physician to manage your respiratory care at home.",
        "why_signia": "Our respiratory therapists bring expertise and compassion to your home.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "social-worker-services": {
        "hero_headline": "Social Worker Services",
        "intro": "Social workers provide emotional support, care coordination, and help navigating resources. They can connect you with community services and support families during difficult transitions.",
        "includes_list": [
            "Emotional support and counseling",
            "Care planning and coordination",
            "Community resource connections",
            "Family support during transitions",
            "Advocacy and care navigation",
        ],
        "who_benefits": "Individuals and families who need support with care planning, resources, or emotional challenges.",
        "how_helps": "Social work services support well-being, reduce stress, and connect you with helpful resources.",
        "what_to_expect": "Your social worker will listen, assess needs, and help you access the support you need.",
        "why_signia": "We understand that care is more than physical—emotional and practical support matter too.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "dietician-nutritionist-services": {
        "hero_headline": "Dietician or Nutritionist Services",
        "intro": "Registered dietitians and nutritionists help with meal planning, dietary modifications, and nutrition education. They can support weight management, diabetes, heart health, and other conditions.",
        "includes_list": [
            "Nutrition assessment and meal planning",
            "Dietary modifications for health conditions",
            "Weight management support",
            "Diabetes and heart health education",
            "In-home consultations",
        ],
        "who_benefits": "Individuals who need help with diet, nutrition, or modified diets for health conditions.",
        "how_helps": "Nutrition services support better health, energy, and quality of life through proper eating.",
        "what_to_expect": "Your dietitian will assess your needs and create a plan that fits your lifestyle and health goals.",
        "why_signia": "We bring nutrition expertise to your home—no need to travel for dietary support.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "medication-management": {
        "hero_headline": "Medication Management Services",
        "intro": "Medication management helps ensure medications are taken correctly and safely. Our team can provide oversight, reminders, and coordination with your pharmacy and physician.",
        "includes_list": [
            "Medication review and oversight",
            "Reminders and adherence support",
            "Pharmacy and physician coordination",
            "Medication reconciliation",
            "Family education on medications",
        ],
        "who_benefits": "Individuals who take multiple medications or need support remembering and managing medications.",
        "how_helps": "Proper medication management supports safety, health, and peace of mind.",
        "what_to_expect": "We work with you and your care team to support safe, consistent medication use.",
        "why_signia": "We take medication safety seriously. Our caregivers are trained to support your medication routine.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "delegated-tasks": {
        "hero_headline": "Delegated Tasks to Unlicensed Personnel",
        "intro": "Some health-related tasks can be delegated by a licensed professional to trained, unlicensed caregivers. These may include certain medication reminders, simple treatments, and other tasks as allowed by Minnesota law.",
        "includes_list": [
            "Tasks delegated by RN or physician",
            "Trained, supervised caregivers",
            "Medication-related tasks",
            "Simple treatments as allowed by law",
            "Full compliance with Minnesota regulations",
        ],
        "who_benefits": "Individuals who need support with specific health tasks that can be safely delegated.",
        "how_helps": "Delegated tasks allow trained caregivers to support your health needs under professional oversight.",
        "what_to_expect": "Tasks are delegated by an RN or other licensed professional. Caregivers are trained and supervised.",
        "why_signia": "We follow Minnesota regulations for delegation and ensure our caregivers are properly trained.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "transfers-mobility": {
        "hero_headline": "Hands-On Assistance with Transfers and Mobility",
        "intro": "Our caregivers provide hands-on help with moving—from bed to chair, chair to standing, or in and out of the shower. Safe transfers reduce fall risk and support independence.",
        "includes_list": [
            "Bed-to-chair transfer assistance",
            "Standing and walking support",
            "Shower and bathroom transfers",
            "Safe transfer techniques",
            "Fall prevention support",
        ],
        "who_benefits": "Individuals who need help moving safely due to weakness, balance issues, or mobility limitations.",
        "how_helps": "Safe transfer assistance supports independence, reduces falls, and protects dignity.",
        "what_to_expect": "Caregivers are trained in safe transfer techniques. We work with you to support your mobility goals.",
        "why_signia": "We prioritize safety and dignity in every transfer. Our caregivers are trained and attentive.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "treatment-therapies": {
        "hero_headline": "Treatment and Therapies",
        "intro": "We provide support for ongoing treatments and therapies ordered by your physician or therapist. This may include exercises, wound care, or other treatments in your home.",
        "includes_list": [
            "Exercise follow-through",
            "Wound care support",
            "Treatment administration",
            "Progress reporting to care team",
            "Between-visit care continuity",
        ],
        "who_benefits": "Individuals who need ongoing treatment support between therapist or nurse visits.",
        "how_helps": "Treatment support helps you stay on track with your care plan and reach your goals.",
        "what_to_expect": "Our caregivers follow the plan developed by your healthcare team and report progress.",
        "why_signia": "We work as part of your care team to ensure continuity and consistency.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "eating-assistance": {
        "hero_headline": "Eating Assistance",
        "intro": "For clients with complicating eating problems—such as swallowing difficulties or physical limitations—we provide supportive eating assistance. Our caregivers are trained to help safely and with dignity.",
        "includes_list": [
            "Supportive eating and feeding",
            "Safe positioning for meals",
            "Pacing and patience",
            "Dietary guideline adherence",
            "Dignity-focused care",
        ],
        "who_benefits": "Individuals who need help with eating due to physical, cognitive, or swallowing challenges.",
        "how_helps": "Eating assistance supports nutrition, safety, and quality of life.",
        "what_to_expect": "Caregivers work at your pace, following any dietary or positioning guidelines from your care team.",
        "why_signia": "We understand that eating is personal. We provide assistance with patience and respect.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "complex-specialty-healthcare": {
        "hero_headline": "Complex or Specialty Healthcare Services",
        "intro": "For individuals with complex or specialty healthcare needs, we may provide skilled support in the home. Services are coordinated with your physician and care team.",
        "includes_list": [
            "Specialized medical care at home",
            "Physician-coordinated care plans",
            "Skilled nursing support",
            "Family and caregiver training",
            "24/7 care coordination",
        ],
        "who_benefits": "Individuals with complex medical needs who want to remain at home with support.",
        "how_helps": "Specialty care at home supports health, safety, and the ability to stay in a familiar place.",
        "what_to_expect": "Care is individualized and coordinated with your healthcare providers.",
        "why_signia": "We work with families and care teams to bring specialized support to your home.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "personal-care-adls": {
        "hero_headline": "Personal Care and Activities of Daily Living",
        "intro": "We provide hands-on assistance with dressing, self-feeding, oral hygiene, hair care, grooming, toileting, and bathing. Our caregivers help with these personal activities in a way that respects your dignity and preferences.",
        "includes_list": [
            "Bathing and dressing assistance",
            "Oral hygiene and grooming",
            "Toileting and incontinence care",
            "Hair care and personal grooming",
            "Respectful, dignity-focused approach",
        ],
        "who_benefits": "Individuals who need help with daily personal care to stay clean, comfortable, and independent.",
        "how_helps": "Personal care support promotes hygiene, comfort, and dignity in daily life.",
        "what_to_expect": "Caregivers assist at your pace and according to your preferences. We focus on what you need.",
        "why_signia": "We treat personal care as a partnership. Your comfort and dignity come first.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "standby-assistance": {
        "hero_headline": "Standby Assistance",
        "intro": "Standby assistance means a caregiver stays within arm's reach while you perform activities—like bathing or transferring—for safety. We're there if you need help, while supporting your independence.",
        "includes_list": [
            "Safety presence during activities",
            "Verbal cues and encouragement",
            "Step-in support when needed",
            "Bathing and transfer safety",
            "Independence-focused approach",
        ],
        "who_benefits": "Individuals who can do most of an activity themselves but need someone nearby for safety.",
        "how_helps": "Standby assistance supports safety and confidence while you remain as independent as possible.",
        "what_to_expect": "Your caregiver will stay close, offer verbal cues if needed, and step in only when necessary.",
        "why_signia": "We balance safety with independence. We're there when you need us.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "medication-reminders": {
        "hero_headline": "Medication Reminders",
        "intro": "Verbal or visual reminders help you take your medications on schedule. Our caregivers can remind you at the right times—supporting consistency without handling medications unless delegated.",
        "includes_list": [
            "Scheduled medication reminders",
            "Verbal or visual cues",
            "Care plan coordination",
            "Consistency support",
            "Adherence tracking",
        ],
        "who_benefits": "Individuals who sometimes forget to take medications and benefit from reminders.",
        "how_helps": "Reminders support medication adherence and peace of mind.",
        "what_to_expect": "Caregivers provide reminders at scheduled times. We work with your care plan.",
        "why_signia": "We understand that remembering medications can be challenging. We're here to help.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "treatment-exercise-reminders": {
        "hero_headline": "Treatment and Exercise Reminders",
        "intro": "Verbal or visual reminders help you stay on track with treatments and exercises ordered by your healthcare provider. Consistency supports better outcomes.",
        "includes_list": [
            "Treatment reminders",
            "Exercise reminders",
            "Standby support if needed",
            "Care plan consistency",
            "Progress reporting",
        ],
        "who_benefits": "Individuals who need reminders to perform treatments or exercises at home.",
        "how_helps": "Reminders support consistency with your care plan and help you reach your goals.",
        "what_to_expect": "Caregivers remind you at the right times. We can also provide standby support if needed.",
        "why_signia": "We help you stay consistent with your care plan—one reminder at a time.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "modified-diets": {
        "hero_headline": "Preparing Modified Diets",
        "intro": "When a licensed health professional orders a modified diet—such as low-sodium, diabetic, or texture-modified—we can prepare meals that follow those guidelines.",
        "includes_list": [
            "Low-sodium and heart-healthy meals",
            "Diabetic diet preparation",
            "Texture-modified diets",
            "Allergy-safe meal prep",
            "Diet order compliance",
        ],
        "who_benefits": "Individuals who need meals prepared according to specific dietary orders.",
        "how_helps": "Proper diet preparation supports health and meets your medical needs.",
        "what_to_expect": "Caregivers follow the diet order and prepare meals in your home.",
        "why_signia": "We take dietary orders seriously and prepare meals with care.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "laundry": {
        "hero_headline": "Laundry",
        "intro": "We help with laundry—washing, drying, folding, and putting away. Clean linens and clothes support comfort and hygiene at home.",
        "includes_list": [
            "Washing and drying",
            "Folding and putting away",
            "Linens and clothing care",
            "Special handling preferences",
            "Regular schedule support",
        ],
        "who_benefits": "Individuals who have difficulty with laundry and benefit from assistance.",
        "how_helps": "Laundry support keeps your home comfortable and your clothes clean.",
        "what_to_expect": "Caregivers handle laundry according to your preferences and schedule.",
        "why_signia": "We take care of the laundry so you can focus on what matters to you.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "housekeeping": {
        "hero_headline": "Housekeeping and Household Chores",
        "intro": "Light housekeeping and household chores help keep your home safe and comfortable. We can help with cleaning, tidying, and basic home maintenance tasks.",
        "includes_list": [
            "Light cleaning and tidying",
            "Dusting and vacuuming",
            "Kitchen and bathroom care",
            "Safe, organized home",
            "Basic maintenance tasks",
        ],
        "who_benefits": "Individuals who need help keeping their home clean and organized.",
        "how_helps": "A clean, tidy home supports safety, comfort, and peace of mind.",
        "what_to_expect": "Caregivers assist with light housekeeping as part of your care plan.",
        "why_signia": "We help maintain a home you can be proud of and comfortable in.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "meal-preparation": {
        "hero_headline": "Meal Preparation",
        "intro": "We help prepare nutritious meals in your home. Whether you need help with cooking, planning meals, or following a special diet, we're here to support you.",
        "includes_list": [
            "Nutritious meal preparation",
            "Meal planning support",
            "Special diet adherence",
            "Grocery and ingredient prep",
            "Your preferences and favorites",
        ],
        "who_benefits": "Individuals who have difficulty preparing meals and want to eat well at home.",
        "how_helps": "Meal preparation supports nutrition, independence, and quality of life.",
        "what_to_expect": "Caregivers prepare meals according to your preferences and any dietary needs.",
        "why_signia": "We believe good food matters. We help you eat well at home.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    "shopping": {
        "hero_headline": "Shopping",
        "intro": "We can help with grocery shopping and other errands. Whether we accompany you or shop on your behalf, we make it easier to get what you need.",
        "includes_list": [
            "Grocery shopping",
            "Accompany or shop on your behalf",
            "List and preference following",
            "Errands and essentials",
            "Carrying and unpacking",
        ],
        "who_benefits": "Individuals who have difficulty getting to the store or carrying groceries.",
        "how_helps": "Shopping assistance supports nutrition, independence, and daily needs.",
        "what_to_expect": "Caregivers help with shopping as part of your care plan—we follow your list and preferences.",
        "why_signia": "We help you get what you need—whether it's groceries, toiletries, or other essentials.",
        "disclaimer": "Services may be available based on assessment, staff availability, and program fit.",
    },
    # Basic 245D Services
    "individual-community-living-supports": {
        "hero_headline": "Individual Community Living Supports",
        "intro": "Individual Community Living Supports (ILCS) help people with disabilities live independently in the community. Services may include support with daily activities, community participation, and skill building.",
        "includes_list": [
            "Daily living support",
            "Community participation",
            "Skill building",
            "Individualized planning",
            "Home and community-based care",
        ],
        "who_benefits": "Individuals with disabilities who want to live in their own home or community setting with support.",
        "how_helps": "ILCS supports independence, community inclusion, and a meaningful life at home.",
        "what_to_expect": "Support is individualized based on your needs and goals. Services are provided in your home or community.",
        "why_signia": "We believe everyone deserves to live in the community with the support they need.",
        "disclaimer": "Services may be available based on assessment, waiver eligibility, staff availability, and program fit.",
    },
    "24-hour-emergency-assistance": {
        "hero_headline": "24-Hour Emergency Assistance",
        "intro": "24-hour emergency assistance provides around-the-clock access to help when you need it. A trained responder can assist in emergencies and connect you with additional support.",
        "includes_list": [
            "Around-the-clock emergency access",
            "Trained responder support",
            "Emergency assessment",
            "Care coordination",
            "Peace of mind for families",
        ],
        "who_benefits": "Individuals who need assurance that help is available at any time.",
        "how_helps": "24-hour assistance supports safety and peace of mind for clients and families.",
        "what_to_expect": "When you call, a trained responder will assess the situation and provide or coordinate help.",
        "why_signia": "We understand that emergencies don't follow a schedule. We're here when you need us.",
        "disclaimer": "Services may be available based on assessment, waiver eligibility, staff availability, and program fit.",
    },
    "companion-services": {
        "hero_headline": "Companion Services",
        "intro": "Companion services provide friendly companionship and socialization. A companion can spend time with you, engage in activities, and help reduce isolation—supporting emotional well-being and community connection.",
        "includes_list": [
            "Friendly conversation and companionship",
            "Activities and hobbies you enjoy",
            "Light assistance with errands or outings",
            "Social engagement and community connection",
            "Emotional support and encouragement",
        ],
        "who_benefits": "Individuals who benefit from companionship, conversation, and social engagement.",
        "how_helps": "Companion services support mental and emotional well-being, reduce loneliness, and encourage engagement.",
        "what_to_expect": "Your companion will spend time with you doing activities you enjoy—conversation, games, outings, or hobbies.",
        "why_signia": "We believe connection matters. Our companions bring warmth and engagement to every visit.",
        "disclaimer": "Services may be available based on assessment, waiver eligibility, staff availability, and program fit.",
    },
    "homemaker-services": {
        "hero_headline": "Homemaker Services",
        "intro": "Homemaker services include light housekeeping, laundry, meal preparation, shopping, and assistance with activities of daily living. We help keep your home running smoothly so you can focus on what matters.",
        "includes_list": [
            "Light housekeeping",
            "Laundry and meal prep",
            "Shopping and errands",
            "Activities of daily living",
            "Household management",
        ],
        "who_benefits": "Individuals who need help with household tasks and daily living activities.",
        "how_helps": "Homemaker services support a safe, comfortable home and daily independence.",
        "what_to_expect": "Caregivers assist with tasks as outlined in your care plan—tailored to your needs.",
        "why_signia": "We help with the tasks that make home life easier—so you can live well at home.",
        "disclaimer": "Services may be available based on assessment, waiver eligibility, staff availability, and program fit.",
    },
    "individualized-home-supports": {
        "hero_headline": "Individualized Home Supports Without Training",
        "intro": "Individualized Home Supports provide personalized in-home support for daily activities, community participation, and health and safety. Services are tailored to your needs and goals.",
        "includes_list": [
            "Personalized in-home support",
            "Daily activities assistance",
            "Community participation",
            "Health and safety support",
            "Individualized care plans",
        ],
        "who_benefits": "Individuals with disabilities who need support to live in their own home.",
        "how_helps": "Individualized supports help you live safely and independently with the right level of assistance.",
        "what_to_expect": "Support is based on your individual plan and may include help with daily activities, community access, and more.",
        "why_signia": "We build support around you—your goals, your schedule, your preferences.",
        "disclaimer": "Services may be available based on assessment, waiver eligibility, staff availability, and program fit.",
    },
    "night-supervision": {
        "hero_headline": "Night Supervision",
        "intro": "Night supervision provides overnight support and monitoring in your home. A trained staff person is present during the night to assist with needs and ensure safety.",
        "includes_list": [
            "Overnight staff presence",
            "Safety monitoring",
            "Medication support",
            "Emergency response",
            "Rest for family caregivers",
        ],
        "who_benefits": "Individuals who need overnight support for safety, medication, or other needs.",
        "how_helps": "Night supervision supports safety and peace of mind during overnight hours.",
        "what_to_expect": "A staff person is present in your home during the night, ready to assist as needed.",
        "why_signia": "We understand that needs don't stop when the sun goes down. We're there through the night.",
        "disclaimer": "Services may be available based on assessment, waiver eligibility, staff availability, and program fit.",
    },
    "respite-care-services": {
        "hero_headline": "Respite Care Services",
        "intro": "Respite care provides short-term relief for family caregivers—from a few hours to several days. A trained caregiver takes over so you can rest, run errands, or simply recharge.",
        "includes_list": [
            "Temporary care in your home or your loved one's home",
            "Medication reminders and supervision",
            "Meal preparation and companionship",
            "Personal care assistance as needed",
            "Flexible scheduling—hours, days, or longer",
        ],
        "who_benefits": "Respite care is essential for family caregivers who need a break. Research shows that regular respite prevents burnout and helps caregivers provide better care long-term.",
        "who_benefits_list": [
            "Family members caring for a loved one with dementia",
            "Parents of children with disabilities",
            "Spouses caring for a partner with chronic illness",
            "Anyone who needs temporary relief from caregiving",
        ],
        "how_helps": "Respite care protects your physical and mental health, prevents caregiver burnout, and gives you time to handle other responsibilities or simply rest—knowing your loved one is safe and well cared for.",
        "how_helps_list": [
            "Prevents caregiver burnout and depression",
            "Allows time for self-care and errands",
            "Peace of mind that your loved one is safe",
            "Enables you to provide better care long-term",
        ],
        "what_to_expect": "We'll work with you to schedule care that fits your needs—whether a few hours weekly or a longer break. Our trained caregivers provide the same quality care you would, so you can step away with confidence.",
        "what_to_expect_list": [
            "Flexible scheduling to fit your needs",
            "Trained, compassionate caregivers",
            "Care tailored to your loved one's routine",
            "Seamless handoff when you return",
        ],
        "why_signia": "Caregivers need care too. We're here to give you the break you deserve—with trained staff who treat your loved one with the same compassion you would.",
        "why_signia_list": [
            "Trained, background-checked caregivers",
            "Flexible scheduling options",
            "Consistent care that follows your routine",
            "We understand—caregivers need support too",
        ],
        "disclaimer": "Services may be available based on assessment, waiver eligibility, staff availability, and program fit.",
    },
}
